version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  assignees:
  - lostcontrol
  ignore:
  - dependency-name: flake8
    versions:
    - 3.8.4
    - 3.9.0
  - dependency-name: adafruit-circuitpython-ads1x15
    versions:
    - 2.2.6
    - 2.2.7
  - dependency-name: adafruit-circuitpython-mcp4725
    versions:
    - 1.4.1
    - 1.4.2
  - dependency-name: transitions
    versions:
    - 0.8.6
    - 0.8.7
  - dependency-name: autopep8
    versions:
    - 1.5.4
    - 1.5.5
  - dependency-name: pytest
    versions:
    - 6.2.1
    - 6.2.2
  - dependency-name: pytest-mock
    versions:
    - 3.5.1
