[tool.ruff]
target-version = "py312"
line-length = 120
lint.select = [
    "C4",  # comprehensions
    "E",   # pycodestyle
    "F",   # pyflakes
    "I",   # isort
    "RUF", # ruff specific
    "UP",  # pyupgrade
    "W",   # pydocstyle warning
    "PT",  # pytest
    "SLF", # self access
    "SIM", # simplify
    "A",   # builtins
    "B",   # bugbear
    "RET", # return
    "RSE", # raise
]
