name: Poupool

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: write
  pull-requests: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        sudo apt-get install -y --no-install-recommends mosquitto
        uv sync
    - name: Lint with pre-commit
      run: |
        uv run pre-commit run -a
    - name: Test with pytest
      run: |
        uv run pytest --cov=controller --cov-report term --junitxml=pytest.xml --cov-report=term-missing:skip-covered test/ | tee pytest-coverage.txt
    - name: Test start the application
      run: |
        uv run python poupool.py --fake-devices --test-start
    - name: Pytest coverage comment
      id: coverage
      uses: MishaKav/pytest-coverage-comment@main
      with:
        pytest-coverage-path: ./pytest-coverage.txt
        junitxml-path: ./pytest.xml
